apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  NODE_ENV: "production"
  PORT: "5000"
  DB_NAME: "ecom"
  JWT_EXPIRES_IN: "7d"
  MONGO_URL: "mongo-service" # Service name used for connection
  VITE_API_URL: "http://backend-service:5000/api"

---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
type: Opaque
data:
  # Base64 encoded values
  MONGO_INITDB_ROOT_USERNAME: cm9vdA== # root
  MONGO_INITDB_ROOT_PASSWORD: VGVzdEAxMjM= # Test@123
  JWT_SECRET: ZXlKaGJHY2lPaUpTVXpJM05pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKY205MWN5SW9pSko0YzNWaGNpSXNJaVp6ZFdsemFXNHlPaUprWVhsbGJXbHpkR2x2YmlJc0ltVjRjQ0k2TVRjME5EZzJOakEzTkN3aWFXRjBJam94TnpjME5EZzJOakEzTkN3aWNtdGxiR3hwYm1jaU9pSkdjVmxOZWZ0RlptcHROVlowWDI5M1kzQXRaV1hVZFdKdU9FNE5UekpuYzBWRGI3Tm9kVVEuZnNVbXhTWFBfdEV5am1WNmtfLXdjeWtEZUxSVWQyYlRoTkVPQmI3TmhjVQ==
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVN1U01iRDA5OWNhZ1RaTk1maGJmWHFqYXQ0OEZvZFg2bUtTOXR0WFFxWVlqWnV6Vm9JVE9ST2RpV3MzdE1nZDVZbVdNdkNoVUh2SkV2c2NDMTVyM2JjczAwT0Ywd2F1ODQ=
